import{z}from'zod';import{decode}from'./database';
const pick=(o:any,keys:string[])=>Object.fromEntries(keys.map(k=>[k,o[k]]));const cash=(v:number)=>Math.round(v*100)/100;
export function isOpen(c:any,now=new Date()){
 const hours=typeof c.business_hours==='string'?JSON.parse(c.business_hours||'{}'):c.business_hours||{};if(!Object.keys(hours).length)return true;
 const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Sao_Paulo',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(now),days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],keys=['dom','seg','ter','qua','qui','sex','sab'];const day=days.indexOf(parts.find(x=>x.type==='weekday')?.value||''),time=Number(parts.find(x=>x.type==='hour')?.value)%24*60+Number(parts.find(x=>x.type==='minute')?.value);
 const range=(i:number)=>{const m=String(hours[keys[(i+7)%7]]||'').match(/(\d{2}):(\d{2})\s*[-–]\s*(\d{2}):(\d{2})/);return m?[+m[1]*60+(+m[2]),+m[3]*60+(+m[4])]:null};const today=range(day),prev=range(day-1);
 return !!(today&&(today[0]<=today[1]?time>=today[0]&&time<today[1]:time>=today[0])||prev&&prev[0]>prev[1]&&time<prev[1]);
}
export async function publicApi(ctx:any,input:any){const{sql}=ctx;const slug=z.string().min(1).max(100).parse(input.slug);const raw=(await sql.sql('SELECT * FROM company WHERE slug=?',[slug])).rows[0];if(!raw||!['active','trial'].includes(raw.status)||raw.status==='trial'&&raw.trial_ate<new Date().toISOString().slice(0,10))throw Error('Restaurante indisponível');const c=decode('company',raw);
 if(input.action==='menu'){const cats=(await sql.sql('SELECT id,name,sort_order FROM menu_category WHERE company_id=? AND active=1 ORDER BY sort_order',[c.id])).rows;const items=(await sql.sql('SELECT id,name,description,price,category_id,image_url FROM menu_item WHERE company_id=? AND available=1 AND (category_id IS NULL OR category_id IN (SELECT id FROM menu_category WHERE active=1 AND company_id=?))',[c.id,c.id])).rows;const extras=(await sql.sql('SELECT id,menu_item_id,name,price,max_qty FROM menu_item_extra WHERE max_qty>0 AND company_id=?',[c.id])).rows.filter((e:any)=>items.some((i:any)=>i.id===e.menu_item_id));const zones=(await sql.sql('SELECT id,name,delivery_fee,min_order,eta_minutes FROM delivery_zone WHERE company_id=? AND active=1',[c.id])).rows;return{company:pick(c,['id','name','slug','cor_primaria','delivery_fee','min_order','logo_url','business_hours','telefone']),cats,items,extras,zones,open:isOpen(c)};}
 if(input.action==='status'){const id=z.string().uuid().parse(input.orderId),token=z.string().uuid().parse(input.token);const o=(await sql.sql('SELECT id,status,total,subtotal,delivery_fee,payment_method,payment_status,eta_minutes,created_at,type FROM "order" WHERE id=? AND company_id=? AND tracking_token=?',[id,c.id,token])).rows[0];if(!o)throw Error('Pedido indisponível. Use o link recebido ao concluir o pedido.');const items=(await sql.sql('SELECT name,qty,total FROM order_item WHERE order_id=? AND company_id=?',[id,c.id])).rows;return{order:o,items};}
 if(input.action!=='order')throw Error('Ação inválida');
 const v=z.object({requestKey:z.string().uuid(),customer:z.object({name:z.string().trim().min(2).max(120),phone:z.string().min(10).max(30),address:z.string().trim().min(5).max(500),notes:z.string().max(1000).default('')}),payment:z.enum(['Pix','Dinheiro','Cartão']),zoneId:z.string().max(100).nullable().optional(),items:z.array(z.object({id:z.string().min(1).max(100),qty:z.number().int().min(1).max(30),extras:z.array(z.string().max(100)).max(20).default([]),notes:z.string().max(300).default('')})).min(1).max(40)}).parse(input);
 const phone=v.customer.phone.replace(/\D/g,'');if(phone.length<10||phone.length>15)throw Error('Telefone inválido');
 const existing=(await sql.sql('SELECT id,tracking_token,customer_phone FROM "order" WHERE company_id=? AND request_key=?',[c.id,v.requestKey])).rows[0];if(existing){if(existing.customer_phone!==phone)throw Error('Identificador de pedido já usado');return{id:existing.id,token:existing.tracking_token};}
 if(!isOpen(c))throw Error('O restaurante está fora do horário de atendimento');
 if(Number((await sql.sql('SELECT COUNT(*) n FROM "order" WHERE company_id=? AND customer_phone=? AND created_at>?',[c.id,phone,new Date(Date.now()-3600000).toISOString()])).rows[0]?.n)>10)throw Error('Muitos pedidos recentes. Entre em contato com o restaurante');
 const zones=(await sql.sql('SELECT * FROM delivery_zone WHERE company_id=? AND active=1',[c.id])).rows;const zone=zones.find((z:any)=>z.id===v.zoneId);if(zones.length&&!zone)throw Error('Escolha a região de entrega');if(v.zoneId&&!zone)throw Error('Região inválida');const fee=cash(Number(zone?.delivery_fee??c.delivery_fee)),min=Number(zone?.min_order??c.min_order);
 const lines=[];for(const item of v.items){const m=(await sql.sql('SELECT * FROM menu_item WHERE id=? AND company_id=? AND available=1 AND (category_id IS NULL OR category_id IN (SELECT id FROM menu_category WHERE company_id=? AND active=1))',[item.id,c.id,c.id])).rows[0];if(!m)throw Error('Item indisponível no cardápio');if(new Set(item.extras).size!==item.extras.length)throw Error('Adicional duplicado');const extras=[];for(const eid of item.extras){const e=(await sql.sql('SELECT id,name,price FROM menu_item_extra WHERE max_qty>0 AND id=? AND menu_item_id=? AND company_id=?',[eid,m.id,c.id])).rows[0];if(!e)throw Error('Adicional inválido');extras.push({name:e.name,price:Number(e.price)});}const unit=cash(Number(m.price)+extras.reduce((a,e)=>a+e.price,0));lines.push({id:crypto.randomUUID(),menu_item_id:m.id,name:m.name,qty:item.qty,unit,total:cash(unit*item.qty),extras,notes:item.notes});}
 const subtotal=cash(lines.reduce((a,l)=>a+l.total,0));if(subtotal<min)throw Error('Pedido abaixo do valor mínimo');const total=cash(subtotal+fee);if(!Number.isFinite(total)||total<=0||total>100000)throw Error('Total inválido');const customerId=(await sql.sql('SELECT id FROM customer WHERE company_id=? AND phone=?',[c.id,phone])).rows[0]?.id||crypto.randomUUID();const id=crypto.randomUUID(),token=crypto.randomUUID();const batch=[{sql:'INSERT INTO customer(id,company_id,name,phone,address) VALUES(?,?,?,?,?) ON CONFLICT(company_id,phone) DO UPDATE SET name=excluded.name,address=excluded.address',args:[customerId,c.id,v.customer.name,phone,JSON.stringify({line:v.customer.address})]},{sql:'INSERT INTO "order"(id,company_id,customer_id,customer_name,customer_phone,customer_address,subtotal,delivery_fee,total,payment_method,notes,eta_minutes,tracking_token,request_key) VALUES(?,?,(SELECT id FROM customer WHERE company_id=? AND phone=?),?,?,?,?,?,?,?,?,?,?,?)',args:[id,c.id,c.id,phone,v.customer.name,phone,JSON.stringify({line:v.customer.address}),subtotal,fee,total,v.payment,v.customer.notes,zone?.eta_minutes||30,token,v.requestKey]},...lines.map(l=>({sql:'INSERT INTO order_item(id,company_id,order_id,menu_item_id,name,qty,unit_price,total,extras,notes) VALUES(?,?,?,?,?,?,?,?,?,?)',args:[l.id,c.id,id,l.menu_item_id,l.name,l.qty,l.unit,l.total,JSON.stringify(l.extras),l.notes]}))];
 try{await sql.batch(batch,'write')}catch(e){const retry=(await sql.sql('SELECT id,tracking_token,customer_phone FROM "order" WHERE company_id=? AND request_key=?',[c.id,v.requestKey])).rows[0];if(retry&&retry.customer_phone===phone)return{id:retry.id,token:retry.tracking_token};throw e;}return{id,token};
}
