import{createClient}from'@blinkdotnew/sdk';import fs from'node:fs';import assert from'node:assert/strict';import{adaptBlinkSql}from'../server/native/sql-adapter';import{Database}from'../server/native/database';
const p=JSON.parse(fs.readFileSync('/tmp/foodcontrol-project-private.json','utf8'));if(p.id!=='foodcontro-student-olj3iewy'||p.workspace_id!=='wsp_vjo17ptb'||p.user_id!=='rv2NqSvTFjh8ivsWDm9opaUo2j62')throw Error('Projeto incorreto');const blink=createClient({projectId:p.id,secretKey:p.api_keys.secret.secret,auth:{mode:'headless'}}),sql=adaptBlinkSql(blink.db);const cid=crypto.randomUUID(),item=crypto.randomUUID(),cat=crypto.randomUUID(),zone=crypto.randomUUID(),extra=crypto.randomUUID(),slug='qa-food-'+Date.now(),base='https://olj3iewy.backend.blink.new';
const http=async(path:string,body?:any,headers:any={})=>fetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined}).then(async r=>({status:r.status,data:await r.json()}));
try{
 const health=await http('/health');assert.equal(health.data.ok,true);console.log('PASS backend/database healthy');const boot=await http('/api/bootstrap');assert.equal(boot.data.configured,true);assert.equal(boot.data.isSuperAdmin,false);console.log('PASS anonymous bootstrap configured not Master');
 const denied=await http('/api/query',{table:'order',action:'select',columns:'*',filters:[],orders:[]});assert.match(denied.data.error.message,/Autenticação/);console.log('PASS anonymous business data denied');
 await sql.batch([{sql:"INSERT INTO company(id,name,slug,status,owner_email)VALUES(?,'Restaurante QA temporário',?,'active','privado@example.com')",args:[cid,slug]},{sql:"INSERT INTO menu_category(id,company_id,name)VALUES(?,?,'QA')",args:[cat,cid]},{sql:"INSERT INTO menu_item(id,company_id,category_id,name,price)VALUES(?,?,?,'Prato fictício QA',20.10)",args:[item,cid,cat]},{sql:"INSERT INTO menu_item_extra(id,company_id,menu_item_id,name,price)VALUES(?,?,?,'Adicional QA',2.35)",args:[extra,cid,item]},{sql:"INSERT INTO delivery_zone(id,company_id,name,delivery_fee,eta_minutes)VALUES(?,?,'Região QA',5.50,30)",args:[zone,cid]}],'write');
 const menu=await http('/api/public',{action:'menu',slug});assert.equal(menu.data.company.owner_email,undefined);assert.equal(menu.data.company.plano,undefined);assert.equal(menu.data.items.length,1);console.log('PASS public menu safe fields');
 const input={action:'order',slug,requestKey:crypto.randomUUID(),zoneId:zone,customer:{name:'Pessoa fictícia QA',phone:'11911112222',address:'Rua QA, 123',notes:''},payment:'Pix',items:[{id:item,qty:2,extras:[extra],notes:'QA'}],total:0};const first=await http('/api/public',input);assert.equal(first.status,200);assert.ok(first.data.id);const again=await http('/api/public',input);assert.deepEqual(first.data,again.data);const orders=(await sql.sql('SELECT * FROM "order" WHERE company_id=?',[cid])).rows;assert.equal(orders.length,1);assert.equal(Number(orders[0].total),50.4);assert.equal((await sql.sql('SELECT COUNT(*) n FROM order_item WHERE company_id=?',[cid])).rows[0].n,1);console.log('PASS atomic order, server prices and idempotency');
 const status=await http('/api/public',{action:'status',slug,orderId:first.data.id,token:first.data.token});assert.equal(status.data.order.total,50.4);assert.equal(status.data.order.customer_phone,undefined);assert.equal(status.data.order.customer_address,undefined);const bad=await http('/api/public',{action:'status',slug,orderId:first.data.id,token:crypto.randomUUID()});assert.equal(bad.status,400);console.log('PASS tracking token required, private fields excluded');
 const invalid=await http('/api/public',{...input,requestKey:crypto.randomUUID(),items:[{id:'invalid',qty:1,extras:[]}]});assert.equal(invalid.status,400);assert.equal((await sql.sql('SELECT COUNT(*) n FROM customer WHERE company_id=?',[cid])).rows[0].n,1);console.log('PASS invalid menu item no orphan records');
 const db=new Database(sql,{userId:'qa',master:false,companyId:cid,role:'admin'});for(const status of['preparo','pronto','saiu','entregue','entregue'])assert.equal((await db.from('order').update({status}).eq('id',first.data.id)).error,null);const cust=(await sql.sql('SELECT total_orders,total_spent FROM customer WHERE company_id=?',[cid])).rows[0];assert.equal(Number(cust.total_orders),1);assert.equal(Number(cust.total_spent),50.4);assert.equal((await sql.sql('SELECT COUNT(*) n FROM financial_entry WHERE company_id=?',[cid])).rows[0].n,0);console.log('PASS repeated state exact customer totals, no invented finance');
 const forged=await http('/api/bootstrap',undefined,{Authorization:'Bearer invalid-token'});assert.equal(forged.status,400);console.log('PASS forged login denied');const anon=createClient({projectId:p.id,publishableKey:p.api_keys.publishable.secret,auth:{mode:'headless'}});await assert.rejects(()=>anon.db.sql('SELECT * FROM "order"'));console.log('PASS direct public SDK SQL denied');
}finally{await sql.batch(['order_item','financial_entry','order','customer','menu_item_extra','menu_item','menu_category','delivery_zone','rider','company_user'].map(t=>({sql:'DELETE FROM "'+t+'" WHERE company_id=?',args:[cid]})).concat([{sql:'DELETE FROM company WHERE id=?',args:[cid]}]),'write');console.log('QA CLEANUP',Number((await sql.sql('SELECT COUNT(*) n FROM company WHERE id=?',[cid])).rows[0].n)===0)}
