/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as MasterRouteImport } from './routes/master'
import { Route as ResetSenhaRouteImport } from './routes/reset-senha'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as AppAiGrowthRouteImport } from './routes/app/ai-growth'
import { Route as AppCardapioRouteImport } from './routes/app/cardapio'
import { Route as AppClientesRouteImport } from './routes/app/clientes'
import { Route as AppConfiguracoesRouteImport } from './routes/app/configuracoes'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppEntregasRouteImport } from './routes/app/entregas'
import { Route as AppEquipeRouteImport } from './routes/app/equipe'
import { Route as AppFinanceiroRouteImport } from './routes/app/financeiro'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppPedidosRouteImport } from './routes/app/pedidos'
import { Route as AppRelatoriosRouteImport } from './routes/app/relatorios'
import { Route as DemoAiGrowthRouteImport } from './routes/demo/ai-growth'
import { Route as DemoCardapioRouteImport } from './routes/demo/cardapio'
import { Route as DemoClientesRouteImport } from './routes/demo/clientes'
import { Route as DemoConfiguracoesRouteImport } from './routes/demo/configuracoes'
import { Route as DemoDashboardRouteImport } from './routes/demo/dashboard'
import { Route as DemoEntregasRouteImport } from './routes/demo/entregas'
import { Route as DemoEquipeRouteImport } from './routes/demo/equipe'
import { Route as DemoFinanceiroRouteImport } from './routes/demo/financeiro'
import { Route as DemoPedidosRouteImport } from './routes/demo/pedidos'
import { Route as DemoRelatoriosRouteImport } from './routes/demo/relatorios'
import { Route as MasterListaRestaurantesRouteImport } from './routes/master/lista-restaurantes'
import { Route as MasterNovoRestauranteRouteImport } from './routes/master/novo-restaurante'
import { Route as MasterPainelRouteImport } from './routes/master/painel'
import { Route as PedirSlugRouteImport } from './routes/pedir.$slug'
import { Route as PedirSlugStatusOrderIdRouteImport } from './routes/pedir.$slug.status.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetSenhaRoute = ResetSenhaRouteImport.update({
  id: '/reset-senha',
  path: '/reset-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAiGrowthRoute = AppAiGrowthRouteImport.update({
  id: '/ai-growth',
  path: '/ai-growth',
  getParentRoute: () => AppRoute,
} as any)
const AppCardapioRoute = AppCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEntregasRoute = AppEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const DemoAiGrowthRoute = DemoAiGrowthRouteImport.update({
  id: '/ai-growth',
  path: '/ai-growth',
  getParentRoute: () => DemoRoute,
} as any)
const DemoCardapioRoute = DemoCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => DemoRoute,
} as any)
const DemoClientesRoute = DemoClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DemoRoute,
} as any)
const DemoConfiguracoesRoute = DemoConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DemoRoute,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DemoRoute,
} as any)
const DemoEntregasRoute = DemoEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => DemoRoute,
} as any)
const DemoEquipeRoute = DemoEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => DemoRoute,
} as any)
const DemoFinanceiroRoute = DemoFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPedidosRoute = DemoPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRelatoriosRoute = DemoRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => DemoRoute,
} as any)
const MasterListaRestaurantesRoute = MasterListaRestaurantesRouteImport.update({
  id: '/lista-restaurantes',
  path: '/lista-restaurantes',
  getParentRoute: () => MasterRoute,
} as any)
const MasterNovoRestauranteRoute = MasterNovoRestauranteRouteImport.update({
  id: '/novo-restaurante',
  path: '/novo-restaurante',
  getParentRoute: () => MasterRoute,
} as any)
const MasterPainelRoute = MasterPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => MasterRoute,
} as any)
const PedirSlugRoute = PedirSlugRouteImport.update({
  id: '/pedir/$slug',
  path: '/pedir/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedirSlugStatusOrderIdRoute = PedirSlugStatusOrderIdRouteImport.update({
  id: '/status/$orderId',
  path: '/status/$orderId',
  getParentRoute: () => PedirSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/app/ai-growth': typeof AppAiGrowthRoute
  '/app/cardapio': typeof AppCardapioRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/entregas': typeof AppEntregasRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/pedidos': typeof AppPedidosRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/demo/ai-growth': typeof DemoAiGrowthRoute
  '/demo/cardapio': typeof DemoCardapioRoute
  '/demo/clientes': typeof DemoClientesRoute
  '/demo/configuracoes': typeof DemoConfiguracoesRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/entregas': typeof DemoEntregasRoute
  '/demo/equipe': typeof DemoEquipeRoute
  '/demo/financeiro': typeof DemoFinanceiroRoute
  '/demo/pedidos': typeof DemoPedidosRoute
  '/demo/relatorios': typeof DemoRelatoriosRoute
  '/master/lista-restaurantes': typeof MasterListaRestaurantesRoute
  '/master/novo-restaurante': typeof MasterNovoRestauranteRoute
  '/master/painel': typeof MasterPainelRoute
  '/pedir/$slug': typeof PedirSlugRouteWithChildren
  '/pedir/$slug/status/$orderId': typeof PedirSlugStatusOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/app/ai-growth': typeof AppAiGrowthRoute
  '/app/cardapio': typeof AppCardapioRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/entregas': typeof AppEntregasRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/pedidos': typeof AppPedidosRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/demo/ai-growth': typeof DemoAiGrowthRoute
  '/demo/cardapio': typeof DemoCardapioRoute
  '/demo/clientes': typeof DemoClientesRoute
  '/demo/configuracoes': typeof DemoConfiguracoesRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/entregas': typeof DemoEntregasRoute
  '/demo/equipe': typeof DemoEquipeRoute
  '/demo/financeiro': typeof DemoFinanceiroRoute
  '/demo/pedidos': typeof DemoPedidosRoute
  '/demo/relatorios': typeof DemoRelatoriosRoute
  '/master/lista-restaurantes': typeof MasterListaRestaurantesRoute
  '/master/novo-restaurante': typeof MasterNovoRestauranteRoute
  '/master/painel': typeof MasterPainelRoute
  '/pedir/$slug': typeof PedirSlugRouteWithChildren
  '/pedir/$slug/status/$orderId': typeof PedirSlugStatusOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/app/ai-growth': typeof AppAiGrowthRoute
  '/app/cardapio': typeof AppCardapioRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/entregas': typeof AppEntregasRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/pedidos': typeof AppPedidosRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/demo/ai-growth': typeof DemoAiGrowthRoute
  '/demo/cardapio': typeof DemoCardapioRoute
  '/demo/clientes': typeof DemoClientesRoute
  '/demo/configuracoes': typeof DemoConfiguracoesRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/entregas': typeof DemoEntregasRoute
  '/demo/equipe': typeof DemoEquipeRoute
  '/demo/financeiro': typeof DemoFinanceiroRoute
  '/demo/pedidos': typeof DemoPedidosRoute
  '/demo/relatorios': typeof DemoRelatoriosRoute
  '/master/lista-restaurantes': typeof MasterListaRestaurantesRoute
  '/master/novo-restaurante': typeof MasterNovoRestauranteRoute
  '/master/painel': typeof MasterPainelRoute
  '/pedir/$slug': typeof PedirSlugRouteWithChildren
  '/pedir/$slug/status/$orderId': typeof PedirSlugStatusOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/reset-senha'
    | '/trocar-senha'
    | '/app/ai-growth'
    | '/app/cardapio'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/entregas'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/onboarding'
    | '/app/pedidos'
    | '/app/relatorios'
    | '/demo/ai-growth'
    | '/demo/cardapio'
    | '/demo/clientes'
    | '/demo/configuracoes'
    | '/demo/dashboard'
    | '/demo/entregas'
    | '/demo/equipe'
    | '/demo/financeiro'
    | '/demo/pedidos'
    | '/demo/relatorios'
    | '/master/lista-restaurantes'
    | '/master/novo-restaurante'
    | '/master/painel'
    | '/pedir/$slug'
    | '/pedir/$slug/status/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/reset-senha'
    | '/trocar-senha'
    | '/app/ai-growth'
    | '/app/cardapio'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/entregas'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/onboarding'
    | '/app/pedidos'
    | '/app/relatorios'
    | '/demo/ai-growth'
    | '/demo/cardapio'
    | '/demo/clientes'
    | '/demo/configuracoes'
    | '/demo/dashboard'
    | '/demo/entregas'
    | '/demo/equipe'
    | '/demo/financeiro'
    | '/demo/pedidos'
    | '/demo/relatorios'
    | '/master/lista-restaurantes'
    | '/master/novo-restaurante'
    | '/master/painel'
    | '/pedir/$slug'
    | '/pedir/$slug/status/$orderId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/reset-senha'
    | '/trocar-senha'
    | '/app/ai-growth'
    | '/app/cardapio'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/entregas'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/onboarding'
    | '/app/pedidos'
    | '/app/relatorios'
    | '/demo/ai-growth'
    | '/demo/cardapio'
    | '/demo/clientes'
    | '/demo/configuracoes'
    | '/demo/dashboard'
    | '/demo/entregas'
    | '/demo/equipe'
    | '/demo/financeiro'
    | '/demo/pedidos'
    | '/demo/relatorios'
    | '/master/lista-restaurantes'
    | '/master/novo-restaurante'
    | '/master/painel'
    | '/pedir/$slug'
    | '/pedir/$slug/status/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  MasterRoute: typeof MasterRouteWithChildren
  ResetSenhaRoute: typeof ResetSenhaRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  PedirSlugRoute: typeof PedirSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-senha': {
      id: '/reset-senha'
      path: '/reset-senha'
      fullPath: '/reset-senha'
      preLoaderRoute: typeof ResetSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ai-growth': {
      id: '/app/ai-growth'
      path: '/ai-growth'
      fullPath: '/app/ai-growth'
      preLoaderRoute: typeof AppAiGrowthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cardapio': {
      id: '/app/cardapio'
      path: '/cardapio'
      fullPath: '/app/cardapio'
      preLoaderRoute: typeof AppCardapioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entregas': {
      id: '/app/entregas'
      path: '/entregas'
      fullPath: '/app/entregas'
      preLoaderRoute: typeof AppEntregasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pedidos': {
      id: '/app/pedidos'
      path: '/pedidos'
      fullPath: '/app/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/demo/ai-growth': {
      id: '/demo/ai-growth'
      path: '/ai-growth'
      fullPath: '/demo/ai-growth'
      preLoaderRoute: typeof DemoAiGrowthRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/cardapio': {
      id: '/demo/cardapio'
      path: '/cardapio'
      fullPath: '/demo/cardapio'
      preLoaderRoute: typeof DemoCardapioRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/clientes': {
      id: '/demo/clientes'
      path: '/clientes'
      fullPath: '/demo/clientes'
      preLoaderRoute: typeof DemoClientesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/configuracoes': {
      id: '/demo/configuracoes'
      path: '/configuracoes'
      fullPath: '/demo/configuracoes'
      preLoaderRoute: typeof DemoConfiguracoesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/dashboard': {
      id: '/demo/dashboard'
      path: '/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/entregas': {
      id: '/demo/entregas'
      path: '/entregas'
      fullPath: '/demo/entregas'
      preLoaderRoute: typeof DemoEntregasRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/equipe': {
      id: '/demo/equipe'
      path: '/equipe'
      fullPath: '/demo/equipe'
      preLoaderRoute: typeof DemoEquipeRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/financeiro': {
      id: '/demo/financeiro'
      path: '/financeiro'
      fullPath: '/demo/financeiro'
      preLoaderRoute: typeof DemoFinanceiroRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/pedidos': {
      id: '/demo/pedidos'
      path: '/pedidos'
      fullPath: '/demo/pedidos'
      preLoaderRoute: typeof DemoPedidosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/relatorios': {
      id: '/demo/relatorios'
      path: '/relatorios'
      fullPath: '/demo/relatorios'
      preLoaderRoute: typeof DemoRelatoriosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/master/lista-restaurantes': {
      id: '/master/lista-restaurantes'
      path: '/lista-restaurantes'
      fullPath: '/master/lista-restaurantes'
      preLoaderRoute: typeof MasterListaRestaurantesRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/novo-restaurante': {
      id: '/master/novo-restaurante'
      path: '/novo-restaurante'
      fullPath: '/master/novo-restaurante'
      preLoaderRoute: typeof MasterNovoRestauranteRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/painel': {
      id: '/master/painel'
      path: '/painel'
      fullPath: '/master/painel'
      preLoaderRoute: typeof MasterPainelRouteImport
      parentRoute: typeof MasterRoute
    }
    '/pedir/$slug': {
      id: '/pedir/$slug'
      path: '/pedir/$slug'
      fullPath: '/pedir/$slug'
      preLoaderRoute: typeof PedirSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedir/$slug/status/$orderId': {
      id: '/pedir/$slug/status/$orderId'
      path: '/status/$orderId'
      fullPath: '/pedir/$slug/status/$orderId'
      preLoaderRoute: typeof PedirSlugStatusOrderIdRouteImport
      parentRoute: typeof PedirSlugRoute
    }
  }
}

interface AppRouteChildren {
  AppAiGrowthRoute: typeof AppAiGrowthRoute
  AppCardapioRoute: typeof AppCardapioRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEntregasRoute: typeof AppEntregasRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPedidosRoute: typeof AppPedidosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiGrowthRoute: AppAiGrowthRoute,
  AppCardapioRoute: AppCardapioRoute,
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEntregasRoute: AppEntregasRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPedidosRoute: AppPedidosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DemoRouteChildren {
  DemoAiGrowthRoute: typeof DemoAiGrowthRoute
  DemoCardapioRoute: typeof DemoCardapioRoute
  DemoClientesRoute: typeof DemoClientesRoute
  DemoConfiguracoesRoute: typeof DemoConfiguracoesRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoEntregasRoute: typeof DemoEntregasRoute
  DemoEquipeRoute: typeof DemoEquipeRoute
  DemoFinanceiroRoute: typeof DemoFinanceiroRoute
  DemoPedidosRoute: typeof DemoPedidosRoute
  DemoRelatoriosRoute: typeof DemoRelatoriosRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAiGrowthRoute: DemoAiGrowthRoute,
  DemoCardapioRoute: DemoCardapioRoute,
  DemoClientesRoute: DemoClientesRoute,
  DemoConfiguracoesRoute: DemoConfiguracoesRoute,
  DemoDashboardRoute: DemoDashboardRoute,
  DemoEntregasRoute: DemoEntregasRoute,
  DemoEquipeRoute: DemoEquipeRoute,
  DemoFinanceiroRoute: DemoFinanceiroRoute,
  DemoPedidosRoute: DemoPedidosRoute,
  DemoRelatoriosRoute: DemoRelatoriosRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface MasterRouteChildren {
  MasterListaRestaurantesRoute: typeof MasterListaRestaurantesRoute
  MasterNovoRestauranteRoute: typeof MasterNovoRestauranteRoute
  MasterPainelRoute: typeof MasterPainelRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterListaRestaurantesRoute: MasterListaRestaurantesRoute,
  MasterNovoRestauranteRoute: MasterNovoRestauranteRoute,
  MasterPainelRoute: MasterPainelRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

interface PedirSlugRouteChildren {
  PedirSlugStatusOrderIdRoute: typeof PedirSlugStatusOrderIdRoute
}

const PedirSlugRouteChildren: PedirSlugRouteChildren = {
  PedirSlugStatusOrderIdRoute: PedirSlugStatusOrderIdRoute,
}

const PedirSlugRouteWithChildren = PedirSlugRoute._addFileChildren(
  PedirSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  EntrarRoute: EntrarRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  MasterRoute: MasterRouteWithChildren,
  ResetSenhaRoute: ResetSenhaRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  PedirSlugRoute: PedirSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
